app = "zkfair-provider"
primary_region = "lhr"

[build]
  dockerfile = "./Dockerfile.server"

[env]
  NODE_ENV = "production"
  PORT = "5000"
  DATABASE_URL = "/app/data/zkfair.db"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "off"
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "data"
  destination = "/app/data"
