app = "zkfair-attestation"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"
  build-context = "../.."

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
